### ISSUE TITLE
Cannot run a bootstrapped app on windows

### ISSUE THREAD

**Issue by gabriel-myob** [MYOB-Technology/starbird-issues#12]
After bootstrapping an app on Windows, npm start does not work as expected.
This happens because of **_'&'_** ( to run "asynchronously commands").

Using [concurrently](https://www.npmjs.com/package/concurrently) - thanks @ivan-myob - could be use to solve this issue.

Any objection on introducing this dependency?

**Comment by richard-lopes** [comment]
Well I wish Windows had good support for basic sh/bash features. Originally it was supposed to work through the Windows 10 Linux Subsystem, but according to Ivan it seems it was not that easy: some stuff being still unsupported.
Since you are the tribe using Windows machine for dev, I am happy for you to contribute those fixes (hope we limit those extra deps 😉 still). Thanks @gabriel-myob.

**Comment by gabriel-myob** [comment]
Sorry, I didn't want to introduce new deps but don't know how to fix it otherwise. 
It seems that Concurrently, can be "globally installed". 
Would you have any preference between devDependency and global?

**Comment by richard-lopes** [comment]
It is all good for one dep 😄 I was just thinking we try to keep that under control. It is so easy to go overboard with NPM. Nope you were right. As a devDependency is the right approach.
